# This is part of a GNU -*- Makefile -*-, included by the Makefiles in
# each of the subdirectories containing kernel code (to be executed by
# the host machine).

include $(TOPDIR)/Makefile.config

AS  = $(HOST_AS)
CPP = $(HOST_CPP)
GCC = $(HOST_GCC)
GXX = $(HOST_GXX)
LD  = $(HOST_LD)

INCPATH = -I$(TOPDIR)
ASFLAGS  = $(HOST_ASFLAGS) $(INCPATH)
CPPFLAGS = $(HOST_CPPFLAGS) $(INCPATH)
CFLAGS   = $(HOST_CFLAGS) $(INCPATH)
LDFLAGS  = $(HOST_LDFLAGS)

# Rules
%.a:
	$(AR) rcv $@ $^

%.o: %.cc
	$(GXX) $(CFLAGS) -c $<

%.o: %.c
	$(GCC) $(CFLAGS) -c $<

%.o: %.s
	$(CPP) $(ASFLAGS) < $< > prep_$<.s
	$(GCC) -c -o $@ prep_$<.s

# Dependencies
.%.d: %.s
	@echo Generating dependencies for $<
	@$(SHELL) -ec '$(CPP) -M $(ASFLAGS) $< \
		| sed '\''s/\($*\)\.o[ :]*/\1.o $@ : /g'\'' > $@; \
		[ -s $@ ] || rm -f $@'

.%.d: %.c
	@echo Generating dependencies for $<
	@$(SHELL) -ec '$(GCC) -M $(CFLAGS) $< \
		| sed '\''s/\($*\)\.o[ :]*/\1.o $@ : /g'\'' > $@; \
		[ -s $@ ] || rm -f $@'

.%.d: %.cc
	@echo Generating dependencies for $<
	@$(SHELL) -ec '$(GXX) -M $(CFLAGS) $< \
		| sed '\''s/\($*\)\.o[ :]*/\1.o $@ : /g'\'' > $@; \
		[ -s $@ ] || rm -f $@'

clean:
	$(RM) $(TOCLEAN) $(PROGRAMS) *.o *~ core prep_*.s .*.d *.a

# Dependences generation
ifneq ($(OBJS),)
ifndef NO_DEP
-include $(OBJS:%.o=.%.d)
endif
endif
