# This is part of a GNU -*- Makefile -*-, to specify system-dependent 
# parts of the Makefile enviroment.
#
# This gets included as part of the GNU-Makefile used in each of 
# the subdirectories.
#
# Depending on your platform, you need to select the correct definition.
# Also, you need to edit the Makefile in the bin subdirectory.

LPR  = lpr
A2PS = a2ps -C --center-title='$$f' --footer="Nachos"
DOXYGEN = doxygen

#CFG = i386-irisa-mac
CFG = i386-istic

################################################
### i386-istic Host
################################################
ifeq ($(CFG),i386-istic)

## Kernel compilation toolchain
HOST_CPP = cpp
HOST_AS  = gcc
HOST_GCC = gcc
HOST_GXX = g++
HOST_ASFLAGS = -P -D_ASM $(HOST_CPPFLAGS)
HOST_CPPFLAGS = -D_REENTRANT -DETUDIANTS_TP
HOST_CFLAGS = -g -Wall -Wshadow $(HOST_CPPFLAGS)
HOST_LDFLAGS = 

## MIPS target compilation toolchain
MIPS_PREFIX=/share/m1info/cross-mips/bin/
MIPS_AS = $(MIPS_PREFIX)mips-gcc -x assembler-with-cpp
MIPS_GCC = $(MIPS_PREFIX)mips-gcc
MIPS_LD = $(MIPS_PREFIX)mips-ld
MIPS_ASFLAGS = $(MIPS_CPPFLAGS) -G0
MIPS_CPPFLAGS = #nil
MIPS_CFLAGS = -Wall -G0 $(MIPS_CPPFLAGS)
MIPS_LDFLAGS = #nil

endif

################################################
### i386-irisa Host
################################################
ifeq ($(CFG),i386-irisa-mac)

## Kernel compilation toolchain
HOST_CPP = cpp
HOST_AS  = gcc
HOST_GCC = gcc
HOST_GXX = g++
HOST_ASFLAGS = -P -D_ASM $(HOST_CPPFLAGS)
HOST_CPPFLAGS = -D_REENTRANT -D_XOPEN_SOURCE
HOST_CFLAGS = -g -Wall -Wshadow $(HOST_CPPFLAGS)
HOST_LDFLAGS = #nil

## MIPS target compilation toolchain
MIPS_PREFIX=/Users/puaut/cross-tool/mips/bin/
MIPS_AS = $(MIPS_PREFIX)mips-cc -x assembler-with-cpp
MIPS_GCC = $(MIPS_PREFIX)mips-cc
MIPS_LD = $(MIPS_PREFIX)mips-ld
MIPS_ASFLAGS = $(MIPS_CPPFLAGS) -G0
MIPS_CPPFLAGS = #nil
MIPS_CFLAGS = -Wall -G0 $(MIPS_CPPFLAGS)
MIPS_LDFLAGS = #nil

endif
