# NOTE: this is a GNU Makefile.  You must use "gmake" rather than "make".

OBJS = directory.o filehdr.o filesys.o fsmisc.o oftable.o openfile.o

archive.a: $(OBJS)

TOPDIR = ../
include $(TOPDIR)/Makefile.kernel
