CC=gcc
CFLAGS=-Wall -Werror -Wextra \
	-Wno-error=div-by-zero \
	-Wno-error=unused-parameter \
	-Wno-error=unused-variable

main: exo1 exo2 exo3

exo1: div0

exo2: tictac

exo3: tictacforever

clean:
	$(RM) div0 tictac tictacforever
