CC=gcc
CFLAGS=-Wall -Werror -Wextra \
	-Wno-error=div-by-zero \
	-Wno-error=unused-parameter \
	-Wno-error=unused-variable\
	-Wno-error=unused-value

main: exo1 exo2 exo3 exo4

exo1: div0

exo2: tictac

exo3: tictacforever

exo4: monitor

clean:
	$(RM) div0 tictac tictacforever monitor
