# NOTE: this is a GNU Makefile.  You must use "gmake" rather than "make".

OBJS = addrspace.o exception.o main.o msgerror.o process.o scheduler.o	\
       synch.o system.o thread.o

archive.a: $(OBJS)

TOPDIR = ../
include $(TOPDIR)/Makefile.kernel
